global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'eventum'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:3001', 'localhost:3003']
        labels:
          group: 'production'