language: go
go:
- 1.13.x
dist: trusty
sudo: true
addons:
  ssh_known_hosts:
  - 163.172.133.90
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deployments/deploy_rsa.enc -out deployments/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp deployments/deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
- sudo apt install -y wget unzip
- wget https://protobuf.googlecode.com/files/protobuf-3.11.4.tar.gz
- tar -xzvf protobuf-3.11.4.tar.gz
- pushd protobuf-3.11.4 && ./configure --prefix=/usr && make && sudo make install && popd

- go install google.golang.org/protobuf/cmd/protoc-gen-go
- go get google.golang.org/grpc
- go get -u github.com/golang/protobuf/protoc-gen-go
- go get github.com/prometheus/client_golang/prometheus
- go get github.com/prometheus/client_golang/prometheus/promauto
- go get github.com/prometheus/client_golang/prometheus/promhttp
- go get github.com/prometheus/client_golang/prometheus/promhttp
- go get -u github.com/mailru/easyjson/...
after_success:
- protoc -I $TRAVIS_BUILD_DIR/api/proto/ $TRAVIS_BUILD_DIR/api/proto/auth.proto --go_out=plugins=grpc:$TRAVIS_BUILD_DIR/api
- easyjson -all $TRAVIS_BUILD_DIR/internal/pkg/models/models.go
- easyjson -all $TRAVIS_BUILD_DIR/internal/pkg/forms/form_*.go
- easyjson $TRAVIS_BUILD_DIR/internal/pkg/security/security.go
- go build -o bin/auth $TRAVIS_BUILD_DIR/cmd/auth/main.go
- go build -o bin/chat $TRAVIS_BUILD_DIR/cmd/chat/main.go
- go build -o bin/server $TRAVIS_BUILD_DIR/cmd/server/main.go
git:
  depth: 9999999
deploy:
- provider: script
  skip_cleanup: true
  script: deployments/deploy.sh
  on:
    branch: bugfix/connection-limit
branches:
  only:
  - master
  - develop
  - bugfix/connection-limit
env:
  global:
  - secure: bMbaC1P9X3XI7xk8PEzqXnMU8+Du9UbHeYFNl2T8ba2yWetenH/VsRzfp+Nx0R98OR+ao20byRCMB7MF8w5HaTC6eSxbQQYsnUdp1qn3/KQ88b3W9ctcTWfoRA77BtzmDo9BL3a28gPenYOlMzHt4X5FUfZTzfdGwxKRvZZI1XMLX5s421gkTp4ZoZUQyu3aaxO2gsqSrLf9W7yOqAwsApTr5TUzafSkunyYksejAQ3QFJCK1f4K3nqRN+9T/diAkjVF24ttfbUNVavd2f8CwKVesIDNmiewrIL5sA5nKkjW7z1bc20zM3er6w8h6G2hAU/6bI/OnIZJkyd/KDJturxvJaxxUGqVYa7YJ8rlteldpEwOP5+tnsbaOesc2VHD+7LJdtF+DZyUohCneeZZCtlMFfoIVh7uFhQGiXxAVd2MrabvYeaWh+rHTamvoWVTA72uLKWf2aoJxCX8o87EzpfeTTHkfStfIHB9a10ELwPUkLLZ18wT1OxCjdxEMhYBGgb8KiwP+YwMIKjDb+NYcg4I1dOKqkTO4+QAgpqHgehYmoGGw15g3sGC3xb+aISHyACW/WUgj62ZdNDPh7Jh3g9dEGEuyKtLqLXbdjLrHIDHDzJ4YEwOGAaA+jfgFqFf1lKBP0iSQkeuaaZy/wn1LQLlz2RECORr7VBjmpuBW1o=
  - secure: QFc6rhe8wPRq7/rRfFTA/iihJKzwXaFdJDGMH9RiTimV6WAbagXc275056p9IX8Lx0pjgdjHZopSnYimgiyQKMRqr9ZCD9dQHdazafX4cqRpe8ingu69ZDkYYpwcLsr58WIHGUzdSjNW3Q3Mr055+08c+pD7LMeGnGWfKYqbA0NaGq2zqk8sV40uJn4EOcKev6O3q+eNeHCcl+LvmSJZvK2S+UH1Y+COgzRzADPum0jyP3vHzlq329rqyG4SpmjgOdh+zrVXFmU9sWtZmPgnFoP4qnfuCjmDidSG1CO1pKM1nUt0bS2nmzExH1jOMs2tmj1+dFRyQSKs4KaO6TFtccnfUwJpSny1qDWb7CCrneM8E4CswHPQX40HR2dDb1/AFzTIGwsHrKRiSE7DodNBlhoAUOthQK9DdbNWcOibB4J+KN5nYDX7AXZ0zHmKSIxVjlvGD9/DVmbVQc85oG5KZ+GOLzJQzkxqkq85kKgUVzmRoLDjn7+ZxQy5J6SyirK0FYuLwdqAUaXEokKzVU80yPN52K/CPfDuhcxA4dr/0gts1bIEQnVlEqCxHHyGiTl3trrjl5KOyqeqHHK8ERaeAaUixAc+PGgfoxyHbF7/zqMLc5JMIf7zYKCoyzaDpR+jyzNLijJKIFMwPtLCLH34QDBdF/JLXbU9NtFB5PDDSkE=
  - secure: biZzH6cx0/l/X76u1yvGW1huo1Xbe6x0PHu7CsTxyeKcGBJFXaknRw2lrsEmwKgoGAghUwvCiZe9vQZDzV80K+4qK1uP43gXEAY2+4gB7WJcF4V6GDmaoSejeiZirlqD/eOI8/QKFusv/45SVZ55AgnknAmE+iC5j9Iy7Dfc/a0hI4HEi9JRLTk0+zT/JcFzHdsS7dV0StwAliEZZGxCgp7Og+zGBt/PeQvSbEC/5N1cZQEtsqwSpdW/B4hY+fHDuMHESTJXUHko68gSKjuClTJzo9Ly6aSzJsrYP5oW6L98hhCA3CoRjOIaNqCZzuzjhJIwTi1S8/kMkmf0AtI+pQRSavga9dP2DCYREm10n+5b5kF7d8iZK3fwLMuEI5t6v5kWpCfQHVBpFS+ZoYENXCq3C0VVHIYzSH1dJ/ogGgvp5RughdsS5O9YTPXTkyJVfiMe3XKL5lEu7nGzUX6p9MdleMg5RK/sB2IqLAYteGPqa6yQYfA94SUPHGvnEIrk9rSst45EnlW7EBuO4P274z0+V2rqCNqIF5JHYPbGbsfm8FAHm/wkwMb4ODb9zpCyfOn9KNjEBHn65nCEPk/z4uVQ3hln/dDiZ8CU9KHiLCbDp4W/NPKnqgWv3inBOjbc37dHi3AOits69pkewt5zB1U9Ph89VcZfkarTXCxork8=
  - DOCKER_COMPOSE_VERSION=1.23.2
