DROP PROCEDURE IF EXISTS add_location(uid INT, latitude FLOAT, longitude FLOAT);
TRUNCATE TABLE profile, tag, user_tag, profile_info, timetable, events, subscribe, event_vote, user_vote, band, message CASCADE;
DROP TABLE IF EXISTS message CASCADE;
DROP TABLE IF EXISTS band CASCADE;
DROP TABLE IF EXISTS event_vote CASCADE;
DROP TABLE IF EXISTS subscribe CASCADE;
DROP TABLE IF EXISTS user_vote CASCADE;
DROP TABLE IF EXISTS timetable CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS profile_info CASCADE;
DROP TABLE IF EXISTS user_tag CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS profile CASCADE;

DROP EXTENSION IF EXISTS postgis_topology;
DROP EXTENSION IF EXISTS postgis;

DROP TYPE IF EXISTS SEX_T;
DROP TYPE IF EXISTS ETYPE_T;

